OESdotnetcore/srcc/OES/OES.SurveyApp/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using OES.Core.Models;
using OES.Core.Services.Interfaces;
using System;
using System.Security.Claims;

namespace OES.SurveyApp.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeQuestionAnswerService _employeeQuestionAnswerService;
        private readonly IAnswerService _answerService;

        public EmployeeController(IEmployeeQuestionAnswerService employeeQuestionAnswerService, IAnswerService answerService)
        {
            _employeeQuestionAnswerService = employeeQuestionAnswerService;
            _answerService = answerService;
        }

        public IActionResult EmployeeQuestions()
        {
            var model = _employeeQuestionAnswerService.GetEmployeeQuestionViewModel(Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            if (TempData["AddStatus"] != null)
            {
                ViewBag.AddStatus = TempData["AddStatus"];
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult EmployeeQuestions([Bind("QuestionId,Value")]  Answer answer)
        {
            if (ModelState.IsValid)
            {
                answer.Value = string.IsNullOrWhiteSpace(Request.Form["answer_input"].ToString()) ? answer.Value : Request.Form["answer_input"].ToString();
                _answerService.AnswerQuestion(answer, Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            }

            TempData["AddStatus"] = "Answer logged, thank you";

            return RedirectToAction("/EmployeeQuestions");
        }

        public IActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ResetPassword([Bind("EmployeeId,NewPassword")] Guid emplyeeId, string password)
        {
            return RedirectToAction("EmployeeQuestions");
        }
    }
}

OESdotnetcore/srcc/OES/OES.SurveyApp/Views/Shared/_Layout.cshtml
@using OES.Core.Services.Interfaces;
@using OES.Data.Entities;
@using Microsoft.AspNetCore.Identity;
@using System.Linq;

@inject IEmployeeService EmployeeService
@inject UserManager<OESWebUser> _userManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OES</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.less" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/admin-question.css" />
    <link rel="stylesheet" href="~/css/assign-question.css" />
    <link rel="stylesheet" href="~/css/employee-management.css" />
    <link rel="stylesheet" href="~/css/vex.css" />
    <link rel="stylesheet" href="~/css/vex-theme-os.css" />
    <link rel="stylesheet" href="~/css/theme.default.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" id="site-navigation">
        <figure id="logo" class="pull-left">
            <a asp-area="" asp-controller=@(User.Identity.IsAuthenticated? "Home" : "Account") asp-action="@(User.Identity.IsAuthenticated? "Index" : "Login")">
                <img src="~/images/oem_logo.png" />
            </a>
        </figure>
        <div class="container">
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown">
                            <button class="dropbtn">@User.Identity.Name</button>
                            <div class="dropdown-content">
                                <a class="btn btn-link navbar-btn navbar-link dd-link" asp-action="EmployeeResetPassword" asp-controller="Account">Reset Password</a>
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="btn btn-link navbar-btn navbar-link dd-link">Logout</button>
                                </form>
                            </div>
                        </li>
                        <li>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @if (User.Identity.IsAuthenticated)
        {
            <nav id="sidebar">
                <div class="sidenav">
                    <ul>
                        @{
                            var claims = await _userManager.GetClaimsAsync(_userManager.FindByEmailAsync(User.Identity.Name).Result);
                            var hasClaim = claims.Any(cl => cl.Value == "Admin");
                        }
                        @if (hasClaim)
                        {
                            <li><a asp-controller="Admin" asp-action="Question"><i class="glyphicon glyphicon-question-sign"></i> Question Management</a></li>
                            <li><a asp-controller="Admin" asp-action="AssignQuestion"><i class="glyphicon glyphicon-tower"></i> Question Assignment</a></li>
                            <li><a asp-controller="Admin" asp-action="EmployeeManagement"><i class="glyphicon glyphicon-user"></i> Employee Management</a></li>
                            <li><a asp-controller="Admin" asp-action="Answers"><i class="glyphicon glyphicon-check"></i> Answers</a></li>
                        }
                        <li><a asp-controller="Employee" asp-action="EmployeeQuestions"><i class="glyphicon glyphicon-question-sign"></i> Answer Questions</a></li>
                    </ul>

                </div>
            </nav>
        }
        <div id="main-content-container">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2019 - Open Energy Survey</p>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/admin-question.js"></script>
    <script src="~/js/assign-question.js"></script>
    <script src="~/js/jquery.tablesorter.js"></script>
    <script src="~/js/jquery.tablesorter.combined.js"></script>
    <script src="~/js/jquery.tablesorter.widgets"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/employee-management.js"></script>
    <script src="~/js/answers.js"></script>
    <script src="~/js/vex.combined.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
</body>
</html>